name: Delete the artifact if it exists
description: Delete an artifact by its name if it exists
inputs:
  artifact:
    description: Any name of artifact
    required: true
  token:
    description: GITHUB_TOKEN
    required: true
runs:
  using: composite
  steps:
    - name: Delete `${{inputs.artifact}}`
      shell: bash
      continue-on-error: true
      run: |
        curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{inputs.token}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository}}/actions/artifacts/${{inputs.artifact}}
