name: Delete the artifact if it exists
description: Delete an artifact by its name if it exists. 'actions/upload-artifact@v4' usually removes artifacts itself when restarting jobs.
inputs:
  artifact:
    description: Any name of artifact
    required: true
runs:
  using: composite
  steps:
    - name: Delete `${{inputs.artifact}}`
      shell: bash
      continue-on-error: true
      run: |
        res=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{github.repository}}/actions/runs/${{github.run_id}}/artifacts?name="${{inputs.artifact}}")

        artifact_id=$(echo "$res" | jq -r 'if .total_count > 0 then .artifacts[0].id else 0 end')

        if [ "$artifact_id" == "0" ]; then
            echo "No artifact to remove was found."
        else
          echo "Found the artifact ID $artifact_id for the ${{inputs.artifact}}."
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{github.repository}}/actions/artifacts/$artifact_id
          echo "The artifact with the ID $artifact_id has been removed."
        fi
