name: 🚀 Deploy Github Pages Demo
on:
  workflow_dispatch:
  repository_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Stop the same workflow actions
concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number || github.run_id}}
  cancel-in-progress: true

# Environment variables for the job
env:
  GODOT_VERSION: 4.1.1
  PROJECT_PATH: dd3d_web_build

jobs:
  build:
    name: 🌐 Build Project
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Prepare Web Build
        run: |
          cp -r addons ${PROJECT_PATH}/addons
          cp -r examples_dd3d ${PROJECT_PATH}/examples_dd3d

      - name: Import Assets
        run: godot -v -e --headless --path ${PROJECT_PATH} --quit || true

      - name: Web Build
        run: |
          mkdir ${GITHUB_WORKSPACE}/_site
          cp ${PROJECT_PATH}/coi-serviceworker.min.js ${GITHUB_WORKSPACE}/_site/coi-serviceworker.min.js
          godot -v --headless --path ${PROJECT_PATH} --export-release web ${GITHUB_WORKSPACE}/_site/index.html

      - name: Fix Permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Site Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages

  deploy:
    name: 🚀 Deploy Site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
